name: compatibility test for Numpy and TensorFlow 1

on:
  # Manual run
  workflow_dispatch:

jobs:
  build:
    name: nt1
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
        python-version: [3.7]
        tensorflow-version: [1.15.0, 1.15.5]
        numpy-version: [1.20.3, 1.21.6]
        include:
          # Python 3.6 only supports Numpy 1.19.5
          - os: ubuntu-20.04
            python-version: '3.6'
            tensorflow-version: 1.15.0
            numpy-version: 1.19.5
          - os: windows-latest
            python-version: '3.6'
            tensorflow-version: 1.15.0
            numpy-version: 1.19.5
          - os: macos-latest
            python-version: '3.6'
            tensorflow-version: 1.15.0
            numpy-version: 1.19.5

          - os: ubuntu-20.04
            python-version: '3.6'
            tensorflow-version: 1.14.0
            numpy-version: 1.19.5
          - os: windows-latest
            python-version: '3.6'
            tensorflow-version: 1.14.0
            numpy-version: 1.19.5
          - os: macos-latest
            python-version: '3.6'
            tensorflow-version: 1.14.0
            numpy-version: 1.19.5

          - os: ubuntu-latest
            python-version: '3.6'
            tensorflow-version: 1.15.0
            numpy-version: 1.19.5
          - os: windows-latest
            python-version: '3.6'
            tensorflow-version: 1.15.0
            numpy-version: 1.19.5
          - os: macos-latest
            python-version: '3.6'
            tensorflow-version: 1.15.0
            numpy-version: 1.19.5

          - os: ubuntu-latest
            python-version: '3.6'
            tensorflow-version: 1.15.5
            numpy-version: 1.19.5
          - os: windows-latest
            python-version: '3.6'
            tensorflow-version: 1.15.5
            numpy-version: 1.19.5
          - os: macos-latest
            python-version: '3.6'
            tensorflow-version: 1.15.5
            numpy-version: 1.19.5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      # exclude TensorFlow in requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install $(sed "/tensorflow*/d" requirements.txt)
          python -m pip install LibRecommender
          python -m pip install tensorflow==${{ matrix.tensorflow-version }}
          python -m pip install numpy==${{ matrix.numpy-version }}

      - name: Install dataclasses for python3.6
        run: python -m pip install dataclasses
        if: matrix.python-version == '3.6'

      - name: Test wheels compatibility on Linux
        run: |
          cp tests/sample_data/sample_movielens_rating.dat /home/runner/work/
          cp tests/compatibility_test.py /home/runner/work/ && cd /home/runner/work/
          python -m compatibility_test
        if: matrix.os == 'ubuntu-20.04'

      - name: Test wheels compatibility on Windows
        run: |
          copy D:\a\LibRecommender\LibRecommender\tests\sample_data\sample_movielens_rating.dat D:\a\
          copy D:\a\LibRecommender\LibRecommender\tests\compatibility_test.py D:\a\ && Set-Location -Path "D:\a\"
          python -m compatibility_test
        if: matrix.os == 'windows-latest'

      - name: Test wheels compatibility on macOS
        run: |
          cp tests/sample_data/sample_movielens_rating.dat /Users/runner/work/
          cp tests/compatibility_test.py /Users/runner/work/ && cd /Users/runner/work/
          python -m compatibility_test
        if: matrix.os == 'macos-latest'
